package main

const SQUARE_WIDTH = 24
const SQUARE_BORDER_WIDTH = 3
const PUZZLE_HEIGHT = 20
const PUZZLE_WIDTH = 10

const SIDEBAR_WIDTH = SQUARE_WIDTH * 6
const WAR_ZONE_WIDTH = PUZZLE_WIDTH * SQUARE_WIDTH

const CANVAS_WIDTH = SIDEBAR_WIDTH + WAR_ZONE_WIDTH
const CANVAS_HEIGHT = PUZZLE_HEIGHT * SQUARE_WIDTH

const FONT_SIZE_SMALL = 14
const FONT_SIZE_LARGE = 34

const INITIAL_FALL_RATE = 1000
const FLOOR_LOCK_RATE = 500
const FALL_RATE_REDUCTION_FACTOR = 3
const LINES_PER_LEVEL = 10

const BUTTON_PADDING_LEFT = 4
