package menu

import "gotris/components"

var graphic = [...]components.Square{
	{Row: 1, Column: 2, Color: components.COLORS[0]},
	{Row: 2, Column: 2, Color: components.COLORS[0]},
	{Row: 3, Column: 2, Color: components.COLORS[0]},
	{Row: 3, Column: 3, Color: components.COLORS[0]},
	{Row: 3, Column: 5, Color: components.COLORS[1]},
	{Row: 3, Column: 6, Color: components.COLORS[1]},
	{Row: 3, Column: 7, Color: components.COLORS[1]},
	{Row: 2, Column: 7, Color: components.COLORS[1]},
	{Row: 1, Column: 7, Color: components.COLORS[1]},
	{Row: 1, Column: 6, Color: components.COLORS[1]},
	{Row: 1, Column: 5, Color: components.COLORS[1]},
	{Row: 2, Column: 5, Color: components.COLORS[1]},
	{Row: 2, Column: 9, Color: components.COLORS[2]},
	{Row: 1, Column: 10, Color: components.COLORS[2]},
	{Row: 3, Column: 10, Color: components.COLORS[2]},
	{Row: 3, Column: 11, Color: components.COLORS[2]},
	{Row: 2, Column: 11, Color: components.COLORS[2]},
	{Row: 5, Column: 5, Color: components.COLORS[3]},
	{Row: 6, Column: 5, Color: components.COLORS[3]},
	{Row: 6, Column: 4, Color: components.COLORS[3]},
	{Row: 7, Column: 5, Color: components.COLORS[3]},
	{Row: 8, Column: 4, Color: components.COLORS[3]},
	{Row: 7, Column: 3, Color: components.COLORS[3]},
	{Row: 5, Column: 7, Color: components.COLORS[4]},
	{Row: 7, Column: 7, Color: components.COLORS[4]},
	{Row: 8, Column: 7, Color: components.COLORS[4]},
	{Row: 8, Column: 9, Color: components.COLORS[5]},
	{Row: 7, Column: 9, Color: components.COLORS[5]},
	{Row: 6, Column: 9, Color: components.COLORS[5]},
	{Row: 6, Column: 10, Color: components.COLORS[5]},
	{Row: 6, Column: 11, Color: components.COLORS[5]},
	{Row: 7, Column: 11, Color: components.COLORS[5]},
	{Row: 8, Column: 11, Color: components.COLORS[5]},
	{Row: 10, Column: 8, Color: components.COLORS[6]},
	{Row: 11, Column: 7, Color: components.COLORS[6]},
	{Row: 12, Column: 8, Color: components.COLORS[6]},
	{Row: 11, Column: 9, Color: components.COLORS[6]},
	{Row: 12, Column: 9, Color: components.COLORS[6]},
	{Row: 13, Column: 9, Color: components.COLORS[6]},
	{Row: 14, Column: 8, Color: components.COLORS[6]},
	{Row: 14, Column: 11, Color: components.COLORS[0]},
	{Row: 14, Column: 12, Color: components.COLORS[0]},
	{Row: 14, Column: 13, Color: components.COLORS[0]},
}
