package config

const SQUARE_WIDTH = 24
const SQUARE_BORDER_WIDTH = 3
const PUZZLE_HEIGHT = 20
const PUZZLE_WIDTH = 10

const SIDEBAR_WIDTH = SQUARE_WIDTH * 6
const WAR_ZONE_WIDTH = PUZZLE_WIDTH * SQUARE_WIDTH

const CANVAS_WIDTH = SIDEBAR_WIDTH + WAR_ZONE_WIDTH
const CANVAS_HEIGHT = PUZZLE_HEIGHT * SQUARE_WIDTH
